Ps08
myriadeinc/emerald pull request #5
Opened 2019-09-16 23:08 UTC by andyjung-dev

2019-09-17 17:30 UTC, hanburger97 requested changes
Please see comments.

2019-09-17 17:30 UTC, hanburger97 commented on src/services/share.service.js
> +  rpcInterface: {
The RPC interface inside of miner.service is really an interface function for our JSON-RPC endpoints (in order to be compliant with the Strantum protocol) for miners to connect to our pool, I don't see the purpose or the need to have this here. 
Furthermore, I don't really see how 'job', 'submit', 'login' and 'keepalive' is relevant for share processing service. And we won't need endpoints for share services, you can just keep then as functions, since we will be calling them within Emerald.

2019-09-17 17:32 UTC, hanburger97 commented
Also, can you please provide a description of the Ticket title, number, and what it briefly does, it will be easier for future references to look at the PR instead of trying to find old tickets in Trello. :)

2019-09-23 02:48 UTC, andyjung-dev commented
Re-did this ticket with better format, see new request for PS-08

2019-09-23 02:48 UTC, closed without merging