PS-20 Adding functionality for submit()
myriadeinc/emerald pull request #9
Opened 2019-10-13 02:37 UTC by andyjung-dev

2019-10-19 21:33 UTC, hanburger97 requested changes
Just a couple of changes on the way our services and api use promises.
Otherwise LGTM, make the small changes and 🚢  it

2019-10-19 21:33 UTC, hanburger97 commented on src/models/miner.model.js
> +            const blockTemplate = getCurrentBlockTemplate();
```suggestion
            return moneroApi.getBlockTemplate()
            .then((blockTemplate) => { ... }
            
```

2019-10-19 21:33 UTC, hanburger97 commented on src/models/miner.model.js
> +            const minerData =
the `return new Promise()` was just a place holder, please dont use it like that, many of our Services, Api calls are already returning promises, let'st just chain them instead.

2019-10-19 21:33 UTC, hanburger97 commented on src/models/miner.model.js
> +                moneroApi.submit(block, function(error, result){
This also returns a promise instead of taking a callback
```suggestion
                return moneroApi.submit(block).then((...) => {...})
```

2019-10-21 07:22 UTC, andyjung-dev commented
Check Slack for latest update

2019-10-27 16:01 UTC, hanburger97 reviewed
Just a couple of small changes, we are almost there!! 😅

2019-10-27 16:01 UTC, hanburger97 commented on src/models/miner.model.js
> +const cryptoNight = mutliHash['cryptonight'];
Would this need to be changed to `randomX` and using a newer version of `multi-hashing` library??

2019-10-27 16:01 UTC, hanburger97 commented on src/services/job.helper.service.js
> +        blockTemplate = getLatestBlockTemplate();
So this method will check in the cache for a previously stored Job string and deserialize it into an Job object?? then we dont need `newJob` no?

2019-10-27 16:01 UTC, hanburger97 commented on src/services/block.reference.service.js
> +            var job = jobHelperService.getFromId(minerData.job_id);
nit: can we use `const` or `let` instead of `var`?

2019-10-27 16:01 UTC, hanburger97 commented on src/services/block.reference.service.js
> +            var block = new Buffer(blockTemplate.buffer.length);
where does this `blockTemplate` comes from? is it suppose to be `job` bc that variable is not used in this function

2019-10-27 16:01 UTC, hanburger97 commented on src/services/job.helper.service.js
> +        cache.put(newJob.id,newJob,"job");
nice!

2019-10-27 16:01 UTC, hanburger97 commented on src/services/job.helper.service.js
> +        cache.put(newJob.id,newJob,"job");
nice!

2019-10-27 16:01 UTC, hanburger97 commented on src/services/job.helper.service.js
> +        return cache.get(`job::${id}`).toJSON();
oh we should probably change the `cache.get` function to support namespacing instead using "job::job_id"

2019-11-02 01:32 UTC, merged